### ISSUE TITLE
Add CONTRIBUTING.md or lock down repo to users not part of the TINF23 IML1 class

### ISSUE THREAD

**Issue by fabischw** [dhbw-ma-ppp/ppp-2023#145]
This is a proposal / 'feature' request to add a CONTRIBUTING.md to provide guidelines for users that are not part of the TINF23 IML1 class if contributions by 'outsiders' are welcome.
Alternatively this issue proposes locking down the repo so 'outsiders' do not interfer with the regular CI/CD-workflow and give students the chance to review each other's code on their own.

While I do believe contributions from non-project members can be benefitial for a project I am not sure if 'outside' contributions are really helping the students learn how to use git, github and python and I do therefore propose either regulating or preventing outside contributions.

**Comment by RubelOS** [comment]
Absolutely right!

**Comment by atrejut** [comment]
should be locked already, let's leave the issue open until Friday to see if any more external reviews come in...
