### ISSUE TITLE
Requesting permission for team members to merge approved PRs

### ISSUE THREAD

**Issue by fabischw** [dhbw-ma-ppp/ppp-2023#228]
This is only about the 'ethical' question, all team members do already have the repo permission to merge approved PRs even if they were opened by others.
As there are many approved, yet unmerged PRs, I'd hereby ask for thoughts on having them merged by team members in order to reduce both the number of open PRs and 'active' branches which would have have purely aesthetic benefits (I suppose we would free up space in the Kilobytes on Microsofts Servers as well but that's not really a benefit to us).
Another benefit would be having more solutions easily accessible if one wants to compare solutions for a specific week.

Would be happy to hear your opinion on this.

**Comment by RubelOS** [comment]
I think this repo is deprecated so you can feel free to merge whatever merge-request you like

**Comment by atrejut** [comment]
Appreciate you cleaning up! :)
I'd recommend adding a comment first ('Will merge this PR in N days if you don't object before then', N ~2-3 or so), but see no issues beyond that.

Thanks!

**Comment by fabischw** [comment]
Alright, thanks for the responses.
Going to leave this Issue open until merging of all approved is completed in case someone wants to comment before or during the process of merging the approved PRs.

**Comment by fabischw** [comment]
Merged the approved PRs; all other PRs either need to be reviewed or are not ready for merging due to requested changes which will have to be implemented.
Closing this issue as completed as the problem was adressed and fixed. Further Repo cleanup efforts can only be done in cooperation with PR authors.
